pipelines:
  - name: build_teamcity_snapshot
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: java
            versions:
              - "8.0.0"

    steps:
      - name: Snapshot
        type: Bash
        configuration:
          inputResources:
            - name: teamcitySnapshotGit
          integrations:
            - name: entplus_deployer
        execution:
          onStart:
            - restore_cache_files m2_home ${HOME}/.m2
          onExecute:
            - cd $res_teamcitySnapshotGit_resourcePath

            # Set env
            - export CI=true
            - export JFROG_CLI_BUILD_NAME=teamcity-artifactory-plugin
            - export JFROG_CLI_BUILD_NUMBER=$run_number
            - export JFROG_CLI_BUILD_PROJECT=ecosys

            # Configure JFrog CLI
            - curl -fL https://install-cli.jfrog.io | sh
            - jf c rm --quiet
            - jf c add internal --url=$int_entplus_deployer_url --user=$int_entplus_deployer_user --password=$int_entplus_deployer_apikey
            - jf mvnc
              --repo-resolve-releases ecosys-teamcity-repos --repo-resolve-snapshots ecosys-teamcity-repos
              --repo-deploy-releases ecosys-oss-release-local --repo-deploy-snapshots ecosys-oss-snapshot-local

            # Run audit
            - jf audit --fail=false

            # Delete former snapshots to make sure the release bundle will not contain the same artifacts
            - jf rt del "ecosys-oss-snapshot-local/org/jfrog/teamcity/teamcity-artifactory-plugin/*" --quiet

            # Run install and publish
            - >
              env -i PATH=$PATH HOME=$HOME
              JFROG_CLI_BUILD_NAME=$JFROG_CLI_BUILD_NAME
              JFROG_CLI_BUILD_NUMBER=$JFROG_CLI_BUILD_NUMBER
              JFROG_CLI_BUILD_PROJECT=$JFROG_CLI_BUILD_PROJECT
              jf rt mvn install -U -B
            - jf rt bag
            - jf rt bp

            # Distribute release bundle
            - jf ds rbc teamcity-artifactory-plugin $NEXT_VERSION --spec=./ci/specs/dev-rbc-filespec.json --spec-vars="version=$NEXT_VERSION" --sign
            - jf ds rbd teamcity-artifactory-plugin $NEXT_VERSION --site="releases.jfrog.io" --sync

          onComplete:
            # Show tests in the *Tests* tab
            - save_tests $res_teamcitySnapshotGit_resourcePath/agent/target/surefire-reports/junitreports
            - save_tests $res_teamcitySnapshotGit_resourcePath/server/target/surefire-reports/junitreports
 
            # Save .m2 cache
            - add_cache_files ${HOME}/.m2 m2_home
