updateCommitStatus: &UPDATE_COMMIT_STATUS update_commit_status teamcityGit --context "$step_name"

pipelines:
  - name: build_teamcity_snapshot
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: java
            versions:
              - "8.0.0"

    steps:
      - name: Snapshot
        type: Bash
        configuration:
          inputResources:
            - name: teamcityGit
          integrations:
            - name: ojo
        execution:
          onStart:
            - *UPDATE_COMMIT_STATUS
            - restore_cache_files m2_home ${HOME}/.m2
          onExecute:
            - cd $res_teamcityGit_resourcePath

            # Set env
            - export CI=true
            - export JFROG_CLI_BUILD_NAME=teamcity-artifactory-plugin
            - export JFROG_CLI_BUILD_NUMBER=$run_number
            # Set M2_HOME
            - MVN_PATH=`which mvn` && export M2_HOME=`readlink -f $MVN_PATH | xargs dirname | xargs dirname`

            # Download JFrog CLI
            - curl -fL https://getcli.jfrog.io | sh && chmod +x jfrog

            # Configure JFrog CLI
            - ./jfrog rt c ojo --url $int_ojo_rt_url --access-token=$int_ojo_rt_token
            - ./jfrog rt mvnc
              --server-id-resolve ojo --repo-resolve-releases libs-release --repo-resolve-snapshots libs-snapshot
              --server-id-deploy ojo --repo-deploy-releases oss-release-local --repo-deploy-snapshots oss-snapshot-local

            # Run install and publish
            - >
              env -i PATH=$PATH M2_HOME=$M2_HOME HOME=$HOME
              JFROG_CLI_BUILD_NAME=$JFROG_CLI_BUILD_NAME
              JFROG_CLI_BUILD_NUMBER=$JFROG_CLI_BUILD_NUMBER
              ./jfrog rt mvn install -U -B
            - ./jfrog rt bag
            - ./jfrog rt bp

          onComplete:
            # Show tests in the *Tests* tab
            - save_tests $res_teamcityGit_resourcePath/agent/target/surefire-reports/junitreports
            - save_tests $res_teamcityGit_resourcePath/server/target/surefire-reports/junitreports

            - *UPDATE_COMMIT_STATUS

            # Save .m2 cache
            - add_cache_files ${HOME}/.m2 m2_home
